modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="pixelshopcurrencies"
version="1.0.0"
displayName="PixelShopCurrencies"
displayURL="https://github.com/CloverCard"
credits="https://github.com/CloverCard"
authors="https://github.com/CloverCard"
description='''
Implements scoreboard currencies into Pixelmon Shopkeepers.
'''

[[dependencies.pixelshopcurrencies]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.pixelshopcurrencies]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"


[[dependencies.pixelshopcurrencies]]
modId="pixelmon"
mandatory=true
versionRange="[9.0.11,)"
ordering="NONE"
side="BOTH"
